export const mvpStyleTemplates = [
  {
    category: 'hair',
    scene: 'casual',
    style: 'natural',
    age_group: 'young',
    name: '自然发型',
    preview_url: '/templates/hair-natural.jpg',
    prompt_extension: 'natural flowing hair, well-groomed, modern hairstyle',
    sort_order: 1,
  },
  {
    category: 'clothing',
    scene: 'casual',
    style: 'casual',
    age_group: 'young',
    name: '休闲日常',
    preview_url: '/templates/casual-daily.jpg',
    prompt_extension: 'casual outfit, jeans and white t-shirt, relaxed fit, everyday wear, clean look',
    sort_order: 2,
  },
  {
    category: 'clothing',
    scene: 'work',
    style: 'formal',
    age_group: 'young',
    name: '职业西装',
    preview_url: '/templates/formal-business.jpg',
    prompt_extension: 'professional business suit, tailored fit, navy blue, crisp white shirt, polished look',
    sort_order: 3,
  },
  {
    category: 'clothing',
    scene: 'sport',
    style: 'sport',
    age_group: 'young',
    name: '运动套装',
    preview_url: '/templates/sport-active.jpg',
    prompt_extension: 'athletic wear, sports outfit, running gear, breathable fabric, dynamic fit',
    sort_order: 4,
  },
];
